spring:
  application:
    name: admin-server
  security:
    user:
      name: "admin"
      password: "admin"
  mail:
    host: smtp.qq.com
    username: 445623551@qq.com
    password: joipcgwrbrxvbiga
  boot:
    admin:
      notify:
        mail:
          to: 445623551@qq.com
          from: 445623551@qq.com
          cc: 505799691@qq.com
      ui:
        title: "应用监控管理"
        brand: "<img src='assets/img/icon-spring-boot-admin.svg'><span>应用监控管理</span>"

server:
  port: 7911
management:
  endpoint:
    shutdown.enabled: true
    health.show-details: always
  endpoints.web.exposure.include: '*'